### ISSUE TITLE
Version 13 has a scheduling problem. It changed the title about 5 times in a very short period. 

### ISSUE THREAD

**Issue by loganintech** [jwolff52/PCMRBot#22]
https://docs.google.com/spreadsheets/d/1ymTNFmmE5P39-ifypM8u3tfEzcA60OSbns3PEdSJ980/pubhtml?gid=955381834&single=true

That is the updated schedule so... I don't really know what to do. Also, isLive is getting a 503 error response and link protection isn't working at all. I know it should be or whatever but it isnt. Sorry if I should rude in just very tired

**Comment by jameswolff96** [comment]
The first part of this is already fixed...and has nothing to do with this project. It's the UpdateSchedule project

**Comment by jameswolff96** [comment]
Hopefully that fixes the problem you described, although it didn't make much sense that it was happenning to begin with...
